project_id = "ososevamkgllbxtsseic"

[functions.create-student-account]
verify_jwt = false

[functions.delete-student]
verify_jwt = false

[functions.register-face]
verify_jwt = false

[functions.verify-face]
verify_jwt = false